// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cap-updater/cap-updater.proto

package capupdater

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CapDownscale struct {
	AccountID            int64    `protobuf:"varint,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	Delta                int32    `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapDownscale) Reset()         { *m = CapDownscale{} }
func (m *CapDownscale) String() string { return proto.CompactTextString(m) }
func (*CapDownscale) ProtoMessage()    {}
func (*CapDownscale) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a946ce3531eb14, []int{0}
}

func (m *CapDownscale) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapDownscale.Unmarshal(m, b)
}
func (m *CapDownscale) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapDownscale.Marshal(b, m, deterministic)
}
func (m *CapDownscale) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapDownscale.Merge(m, src)
}
func (m *CapDownscale) XXX_Size() int {
	return xxx_messageInfo_CapDownscale.Size(m)
}
func (m *CapDownscale) XXX_DiscardUnknown() {
	xxx_messageInfo_CapDownscale.DiscardUnknown(m)
}

var xxx_messageInfo_CapDownscale proto.InternalMessageInfo

func (m *CapDownscale) GetAccountID() int64 {
	if m != nil {
		return m.AccountID
	}
	return 0
}

func (m *CapDownscale) GetDelta() int32 {
	if m != nil {
		return m.Delta
	}
	return 0
}

type DownscaleResponse struct {
	Accepted             bool     `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownscaleResponse) Reset()         { *m = DownscaleResponse{} }
func (m *DownscaleResponse) String() string { return proto.CompactTextString(m) }
func (*DownscaleResponse) ProtoMessage()    {}
func (*DownscaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38a946ce3531eb14, []int{1}
}

func (m *DownscaleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownscaleResponse.Unmarshal(m, b)
}
func (m *DownscaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownscaleResponse.Marshal(b, m, deterministic)
}
func (m *DownscaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownscaleResponse.Merge(m, src)
}
func (m *DownscaleResponse) XXX_Size() int {
	return xxx_messageInfo_DownscaleResponse.Size(m)
}
func (m *DownscaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownscaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownscaleResponse proto.InternalMessageInfo

func (m *DownscaleResponse) GetAccepted() bool {
	if m != nil {
		return m.Accepted
	}
	return false
}

func init() {
	proto.RegisterType((*CapDownscale)(nil), "capupdater.CapDownscale")
	proto.RegisterType((*DownscaleResponse)(nil), "capupdater.DownscaleResponse")
}

func init() {
	proto.RegisterFile("proto/cap-updater/cap-updater.proto", fileDescriptor_38a946ce3531eb14)
}

var fileDescriptor_38a946ce3531eb14 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x8b, 0x83, 0x40,
	0x10, 0x85, 0xcf, 0x3b, 0x3c, 0xbc, 0xc1, 0xc6, 0xe5, 0x0a, 0x91, 0x04, 0xc4, 0x34, 0x36, 0x51,
	0x48, 0xfe, 0x41, 0xb4, 0xb1, 0xdd, 0x90, 0x36, 0x30, 0x19, 0xa7, 0x08, 0x88, 0x3b, 0xe8, 0x9a,
	0xfc, 0xfd, 0x80, 0x06, 0x15, 0xd2, 0xed, 0x7b, 0x0f, 0xbe, 0xfd, 0x06, 0x76, 0xd2, 0x19, 0x6b,
	0x72, 0x42, 0xd9, 0x0f, 0x52, 0xa3, 0xe5, 0x6e, 0xfd, 0xce, 0xc6, 0x55, 0x01, 0xa1, 0xbc, 0x9b,
	0xe4, 0x04, 0x7e, 0x81, 0x52, 0x9a, 0x67, 0xdb, 0x13, 0x36, 0xac, 0x36, 0xf0, 0x87, 0x44, 0x66,
	0x68, 0x6d, 0x55, 0x86, 0x4e, 0xec, 0xa4, 0x3f, 0x7a, 0x29, 0xd4, 0x3f, 0xb8, 0x35, 0x37, 0x16,
	0xc3, 0xef, 0xd8, 0x49, 0x5d, 0x3d, 0x85, 0x24, 0x87, 0x60, 0x06, 0x68, 0xee, 0xc5, 0xb4, 0x3d,
	0xab, 0x08, 0x3c, 0x24, 0x62, 0xb1, 0x5c, 0x8f, 0x1c, 0x4f, 0xcf, 0xf9, 0x70, 0x85, 0xa0, 0x40,
	0xb9, 0x4c, 0x0a, 0x67, 0xee, 0x1e, 0x77, 0x62, 0x55, 0x81, 0x3f, 0x53, 0x0a, 0x14, 0x15, 0x66,
	0x8b, 0x66, 0xb6, 0x76, 0x8c, 0xb6, 0xeb, 0xe5, 0xe3, 0xe7, 0xe4, 0xeb, 0xf6, 0x3b, 0xde, 0x79,
	0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x24, 0x2e, 0x81, 0x95, 0x0e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for CapUpdaterService service

type CapUpdaterServiceClient interface {
	DownscaleCap(ctx context.Context, in *CapDownscale, opts ...client.CallOption) (*DownscaleResponse, error)
}

type capUpdaterServiceClient struct {
	c           client.Client
	serviceName string
}

func NewCapUpdaterServiceClient(serviceName string, c client.Client) CapUpdaterServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "capupdater"
	}
	return &capUpdaterServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *capUpdaterServiceClient) DownscaleCap(ctx context.Context, in *CapDownscale, opts ...client.CallOption) (*DownscaleResponse, error) {
	req := c.c.NewRequest(c.serviceName, "CapUpdaterService.DownscaleCap", in)
	out := new(DownscaleResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CapUpdaterService service

type CapUpdaterServiceHandler interface {
	DownscaleCap(context.Context, *CapDownscale, *DownscaleResponse) error
}

func RegisterCapUpdaterServiceHandler(s server.Server, hdlr CapUpdaterServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&CapUpdaterService{hdlr}, opts...))
}

type CapUpdaterService struct {
	CapUpdaterServiceHandler
}

func (h *CapUpdaterService) DownscaleCap(ctx context.Context, in *CapDownscale, out *DownscaleResponse) error {
	return h.CapUpdaterServiceHandler.DownscaleCap(ctx, in, out)
}
